name: flutter_agnostic
description: Package to make platform-dependent usage between Material and Cupertino widgets in the same app easier.
version: 0.4.0
homepage: https://github.com/quinnjr/flutter_agnostic
repository: https://github.com/quinnjr/flutter_agnostic

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  test:

flutter:
